// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thetaradix.proto

package thetaradix

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterRequest struct {
	Mail                 string   `protobuf:"bytes,1,opt,name=mail,proto3" json:"mail,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_108ea66c53471098, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PleaseVerifyPassword bool     `protobuf:"varint,2,opt,name=pleaseVerifyPassword,proto3" json:"pleaseVerifyPassword,omitempty"`
	Jwt                  string   `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_108ea66c53471098, []int{1}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RegisterReply) GetPleaseVerifyPassword() bool {
	if m != nil {
		return m.PleaseVerifyPassword
	}
	return false
}

func (m *RegisterReply) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *RegisterReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "thetaradix.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "thetaradix.RegisterReply")
}

func init() { proto.RegisterFile("thetaradix.proto", fileDescriptor_108ea66c53471098) }

var fileDescriptor_108ea66c53471098 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x5b, 0x34, 0x0e, 0x8a, 0x65, 0xf0, 0x10, 0xeb, 0x45, 0xf6, 0xe4, 0xa9, 0x87,
	0xfa, 0x06, 0xde, 0x85, 0x12, 0xc4, 0x9b, 0x87, 0xb8, 0x1d, 0x6b, 0x34, 0x6d, 0xe2, 0x4c, 0x4a,
	0xdd, 0xe7, 0xf0, 0x85, 0x25, 0xd1, 0xb5, 0xab, 0xec, 0x6d, 0xfe, 0xff, 0x83, 0x99, 0xe1, 0x83,
	0x49, 0x7a, 0xa1, 0x64, 0xd9, 0x2e, 0xdd, 0xc7, 0x2c, 0x72, 0x48, 0x01, 0x61, 0xdf, 0xd4, 0x8f,
	0x70, 0x66, 0x68, 0xe5, 0x24, 0x11, 0x1b, 0x7a, 0xdf, 0x92, 0x24, 0x44, 0x18, 0xaf, 0xad, 0xf3,
	0xba, 0xba, 0xaa, 0xae, 0x8f, 0x4d, 0x99, 0x71, 0x0a, 0x6a, 0xe3, 0x9a, 0xb7, 0x8d, 0x5d, 0x93,
	0x1e, 0x95, 0xfe, 0x37, 0x67, 0x16, 0xad, 0xc8, 0x2e, 0xf0, 0x52, 0x1f, 0x7c, 0xb3, 0x2e, 0xd7,
	0x9f, 0x15, 0x9c, 0xee, 0xf7, 0x47, 0xdf, 0xa2, 0x86, 0x23, 0xd9, 0x36, 0x0d, 0x89, 0x94, 0x03,
	0xca, 0x74, 0x11, 0xe7, 0x70, 0x1e, 0x3d, 0x59, 0xa1, 0x07, 0x62, 0xf7, 0xdc, 0x2e, 0xfa, 0x3b,
	0x95, 0x19, 0x64, 0x38, 0x81, 0xd1, 0xeb, 0x2e, 0xfd, 0xbc, 0x94, 0x47, 0xac, 0xe1, 0x84, 0x98,
	0x03, 0xdf, 0x91, 0x88, 0x5d, 0x91, 0x1e, 0x17, 0xf4, 0xa7, 0x9b, 0x2f, 0x00, 0xee, 0xb3, 0x02,
	0x93, 0x15, 0xe0, 0x2d, 0xa8, 0xee, 0x45, 0xbc, 0x9c, 0xf5, 0x6c, 0xfd, 0x13, 0x33, 0xbd, 0x18,
	0x86, 0xd1, 0xb7, 0x4f, 0x87, 0xc5, 0xec, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xad,
	0x5b, 0xd1, 0x6d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ThetaRadixClient is the client API for ThetaRadix service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ThetaRadixClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
}

type thetaRadixClient struct {
	cc *grpc.ClientConn
}

func NewThetaRadixClient(cc *grpc.ClientConn) ThetaRadixClient {
	return &thetaRadixClient{cc}
}

func (c *thetaRadixClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/thetaradix.ThetaRadix/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThetaRadixServer is the server API for ThetaRadix service.
type ThetaRadixServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
}

func RegisterThetaRadixServer(s *grpc.Server, srv ThetaRadixServer) {
	s.RegisterService(&_ThetaRadix_serviceDesc, srv)
}

func _ThetaRadix_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThetaRadixServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thetaradix.ThetaRadix/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThetaRadixServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ThetaRadix_serviceDesc = grpc.ServiceDesc{
	ServiceName: "thetaradix.ThetaRadix",
	HandlerType: (*ThetaRadixServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ThetaRadix_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thetaradix.proto",
}
